version: "3.3"

services:

  api:
    build:
      context: .
    image: kata
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - stack_network


  gophertown:
    build:
      context: .
    image: kata
    volumes:
      - ./:/app
    command: "npm run dev"
    env_file: docker-compose.env
    environment:
      SERVICES: gopher, town
    depends_on:
      - nats
    networks:
      - stack_network

  greeter:
    build:
      context: .
    image: kata
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - nats
    networks:
      - stack_network

  products:
    build:
      context: .
    image: kata
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
      - nats
    networks:
      - stack_network

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - stack_network

  nats:
    image: nats:2
    networks:
      - stack_network

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - stack_network
      - default

networks:
  stack_network:
    driver: bridge

volumes:
  data:
